CREATE DATABASE DIM_FACT_TRADING;

USE DIM_FACT_TRADING;

CREATE TABLE DIM_COUNTRY (
	COUNTRY_ID INT IDENTITY(1,1) PRIMARY KEY,
    COUNTRY_CODE CHAR(3),
    COUNTRY_NAME VARCHAR(100),
    REGION VARCHAR(500),
    INCOME_GROUP VARCHAR(500),
    SPECIAL_NOTES VARCHAR(1000),
	CREATE_DATE DATETIME,
	UPDATE_DATE DATETIME
);

CREATE TABLE DIM_INDICATOR (
	INDICATOR_ID INT IDENTITY(1,1) PRIMARY KEY,
    INDICATOR_CODE VARCHAR(100),
    INDICATOR_NAME VARCHAR(100),
    SOURCE_ORGANIZATION VARCHAR(200),
    SOURCE_NOTE VARCHAR(200),
	CREATE_DATE DATETIME,
	UPDATE_DATE DATETIME
);

CREATE TABLE DIM_YEAR (
    YEAR_ID INT IDENTITY(1,1) PRIMARY KEY,
    YEAR INT UNIQUE,
	DECADE VARCHAR(10),
	CREATE_DATE DATETIME,
	UPDATE_DATE DATETIME
);

CREATE TABLE FACT_TRADE (
    TRADE_ID INT IDENTITY(1,1) PRIMARY KEY,
    COUNTRY_ID INT,
    INDICATOR_ID INT NOT NULL,
    YEAR_ID INT NOT NULL,
    TRADE_VALUE DECIMAL(20,15),
	CREATE_DATE DATETIME,
	UPDATE_DATE DATETIME
);

ALTER TABLE FACT_TRADE 
ADD CONSTRAINT FK_FACT_TRADE_COUNTRY FOREIGN KEY (COUNTRY_ID) 
REFERENCES DIM_COUNTRY(COUNTRY_ID);

ALTER TABLE FACT_TRADE 
ADD CONSTRAINT FK_FACT_TRADE_INDICATOR FOREIGN KEY (INDICATOR_ID) 
REFERENCES DIM_INDICATOR(INDICATOR_ID);

ALTER TABLE FACT_TRADE 
ADD CONSTRAINT FK_FACT_TRADE_YEAR FOREIGN KEY (YEAR_ID) 
REFERENCES DIM_YEAR(YEAR_ID);

DROP TABLE IF EXISTS FACT_TRADE;
DROP TABLE IF EXISTS DIM_YEAR;
DROP TABLE IF EXISTS DIM_INDICATOR;
DROP TABLE IF EXISTS DIM_COUNTRY;

SELECT * FROM DIM_COUNTRY;
SELECT * FROM DIM_YEAR;
SELECT * FROM DIM_INDICATOR;
SELECT * FROM FACT_TRADE;