CREATE DATABASE STG_TRADING;

USE STG_TRADING;
---------------------------------------------------------------------------------------------

CREATE TABLE STG_TRAD(
	COUNTRY_NAME VARCHAR(100),
	COUNTRY_CODE CHAR(3),
	INDICATOR_NAME VARCHAR(50),
	INDICATOR_CODE VARCHAR(50),
	YEAR INT,
	TRADE_VALUE DECIMAL(20,15)
);

CREATE TABLE STG_TRNR(
	COUNTRY_NAME VARCHAR(100),
	COUNTRY_CODE CHAR(3),
	INDICATOR_NAME VARCHAR(50),
	INDICATOR_CODE VARCHAR(50),
	YEAR INT,
	TRADE_VALUE DECIMAL(20,15)
);

CREATE TABLE STG_COUNTRY(
	COUNTRY_CODE VARCHAR(150),
	REGION VARCHAR(500),
	INCOME_GROUP VARCHAR(500),
	SPECIAL_NOTES VARCHAR(1000),
	TABLE_NAME VARCHAR(100)
);

CREATE TABLE STG_INDICATOR_TRAD(
	INDICATOR_CODE VARCHAR(100),
	INDICATOR_NAME VARCHAR(100),
	SOURCE_NOTE VARCHAR(400),
	SOURCE_ORGANIZATION VARCHAR(200)
);

CREATE TABLE STG_INDICATOR_TRNR(
	INDICATOR_CODE VARCHAR(100),
	INDICATOR_NAME VARCHAR(100),
	SOURCE_NOTE VARCHAR(400),
	SOURCE_ORGANIZATION VARCHAR(200)
);


-- TRUNCATE COMMANDS
TRUNCATE TABLE STG_TRAD;
TRUNCATE TABLE STG_TRNR;

TRUNCATE TABLE STG_COUNTRY;

TRUNCATE TABLE STG_INDICATOR_TRAD;
TRUNCATE TABLE STG_INDICATOR_TRNR;

-- DROP COMMANDS
DROP TABLE STG_TRAD;
DROP TABLE STG_TRNR;

DROP TABLE STG_COUNTRY;

DROP TABLE STG_INDICATOR_TRAD;
DROP TABLE STG_INDICATOR_TRNR;

-- SELECT STATEMENTS TO VERIFY
select * from STG_TRAD order by COUNTRY_NAME, YEAR;
select * from STG_TRNR order by COUNTRY_NAME, YEAR;

select * from STG_COUNTRY;

select * from STG_INDICATOR_TRAD;
select * from STG_INDICATOR_TRNR;

select * from STG_COUNTRY;